apiVersion: v1
kind: Service
metadata:
  name: flatnotes-svc
  labels:
    app: flatnotes
spec:
  type: ClusterIP
  selector:
    app: flatnotes
  ports:
    - port: 8080
      targetPort: 8080
      name: http
